Universite/Pages/SaisieNotes/NotesPageModel.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Universite.Data;
using Universite.Models;

namespace Universite.Pages.SaisieNotes
{
    public class NotesPageModel : PageModel
    {
        public Dictionary<Etudiant, String> etude = new Dictionary<Etudiant, String>();

        public void SearchNotes(ApplicationDbContext context, UE ue)
        {
            var etudiant = from et in context.Etudiant where et.FormationID == ue.FormationID select et;
            var note = from n in context.Note where n.UEID == ue.ID orderby n.EtudiantID ascending select n;
            String value;

            foreach(Etudiant e in etudiant)
            {
                value = "";
                foreach (Note n in note)
                {
                    if (n.EtudiantID == e.ID)
                        value = n.Valeur + "";
                }
                etude.Add(e, value);
            }
        }
    }
}

Universite/Pages/SaisieNotes/SaisieNotes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Universite.Models;

namespace Universite.Pages.SaisieNotes
{
    [Authorize(Roles = "Enseignant")]
    public class SaisieNotesModel : NotesPageModel
    {
        private readonly Universite.Data.ApplicationDbContext _context;

        public SaisieNotesModel(Universite.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // Les données à afficher
        public IList<UE> LesUEs { get; set; }

        // L’UE sélectionné
        [BindProperty]
        public int UEID { get; set; }

        // Contenu de la combo box
        public List<SelectListItem> SelectUEsData { get; private set; }
        public async Task OnGetAsync()
        {
            LesUEs = await _context.UE.ToListAsync();

            // Initialisation de la page. Chargement de la liste déroulante des UEs
            SelectUEsData = new List<SelectListItem>();
            SelectUEsData.Add(new SelectListItem
            {
                Text = "Choisir une UE",
                Value = ""
            });

            foreach (UE u in LesUEs)
            {
                SelectUEsData.Add(new SelectListItem
                {
                    Text = u.NomComplet,
                    Value = u.ID.ToString()
                });
            }

            // Remplissage de la vue
            ViewData["SelectUEsData"] = new SelectList(SelectUEsData, "Value", "Text");
            if (ue != null)
                SearchNotes(_context, ue);
        }

        public UE ue { get; set; }

        public async Task<IActionResult> OnPostLoadAsync()
        {
            if (UEID == 0)
            {
                await OnGetAsync();
                return Page();
            }

            ue = await _context.UE.Include(e => e.LaFormation).AsNoTracking().FirstOrDefaultAsync(m => m.ID == UEID);

            await OnGetAsync();

            return Page();
        }

        [BindProperty]
        public int[] etudiantID { get; set; }

        [BindProperty]
        public String[] Notes { get; set; }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            if (etudiantID != null)
            {
                for (int i = 0; i < etudiantID.Length; i++)
                { 
                    var note = from n in _context.Note where n.UEID == UEID && n.EtudiantID == etudiantID[i] select n;

                    Note Note = new Note();
                    foreach (Note n in note)
                        Note = n;

                    if (!String.IsNullOrEmpty(Notes[i]))
                    {
                        try
                        {
                            if (Note.ID == 0)
                            {
                                Note noteEtud = new Note();
                                noteEtud.ID = 0;
                                noteEtud.Valeur = float.Parse(Notes[i].Replace('.', ','));
                                noteEtud.UEID = UEID;
                                noteEtud.EtudiantID = etudiantID[i];

                                _context.Note.Add(noteEtud);
                                await _context.SaveChangesAsync();
                            }
                            else
                            {
                                Note.Valeur = float.Parse(Notes[i].Replace('.', ','));
                                _context.Attach(Note).State = EntityState.Modified;
                                await _context.SaveChangesAsync();
                            }
                        }catch (Exception e)
                        {
                            //rien
                        }
                        
                    }
                    else
                    {
                        if (Note.ID != 0)
                        {
                            _context.Note.Remove(Note);
                            await _context.SaveChangesAsync();
                        }
                    }
                }
            }

            await OnPostLoadAsync();
            return Page();
        }
    }
}

Universite/Pages/SaisieNotes/SaisieNotes.cshtml
@page
@model Universite.Pages.SaisieNotes.SaisieNotesModel
@{
    ViewData["Title"] = "Saisie";
}

<h2>Saisie des notes</h2>
<br />
<b>Etape 1</b>
<p>Veuillez choisir l'UE pour la saisie des notes <br /> Cliquez sur charger les notes</p>
<br />
<form method="post">
    <div class="form-group">
        <select asp-for="UEID" class="form-control" asp-items="ViewBag.SelectUEsData"></select>
    </div>
    <div class="form-group">
        <button asp-page-handler="load">Charger les notes</button>
    </div>
</form>

<b>Etape 2</b>
<p>
    Pensez à enregistrer vos modifications avant de quitter la page ou de changer d'UE
    Veuillez saisir/modifier des notes de l'UE : @{
        try
        {
            @Model.ue.NomComplet
            <br />
        }
        catch (Exception e) { }
    }
</p>
<br />
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nom étudiant
                </th>
                <th>
                    Note /20
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (KeyValuePair<Universite.Models.Etudiant, string> kvp in Model.etude)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => kvp.Key.Nom)
                        @Html.DisplayFor(modelItem => kvp.Key.Prenom)
                    </td>
                    <td>
                        <input asp-for="@kvp.Key.ID" name="etudiantID" type="hidden" />
                        <input asp-for="@Model.ue.ID" name="UEID" type="hidden" />
                        <div class="form-group">
                            <input asp-for="@kvp.Value" name="Notes" />
                            <span asp-validation-for="@kvp.Value" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="form-group">
        <button asp-page-handler="Update">Mettre à jour les notes</button>
    </div>
</form>